### PR TITLE
Make a more specific exception

### PR DESCRIPTION
**Pull request by Skylled**
I always wrap my RNCryptor code in a try, except clause, because bad data is somewhat commonplace in my program. It would be nice to be 100% certain that the exception is caused by bad data and handle accordingly, rather than the exception being handled as if it were bad data when it could be a variety of other problems. With this minor change, I can catch the DecryptionError instead of any generic Exception.

### CODE REVIEW

**Comment by ykalchevskiy** [comment]
Looks reasonable! But I think we can improve your idea a little: add base `RNCryptorError` exception for future cases and make simple hierarchy with `DecryptionError`. I can do it myself or let you update this pull request. What do you think? Also it would be great if you provide a simple docstring for `DecryptionError`.

**Comment by Skylled** [comment]
Sounds easy enough. I'm not exactly a master of Python just yet, but how does that look now?

**Comment by ykalchevskiy** [comment]
Almost perfect! There are 2 things that we may do:
* get rid of the `pass` statement;
* end docstrings with a period to fit [PEP-257](https://www.python.org/dev/peps/pep-0257/#id16).

@Skylled, I hope these actions don't disturb you a lot, but you the first commiter to this repo except maintainers and we don't have neither a contribution guide nor automatic checks on formatting. I will try to fix it soon. Thanks for patience.

**Comment by Skylled** [comment]
I certainly don't mind. I love the idea of being able to contribute, while learning more along the way. The RNC package is core to the security of my main project right now, so anything I can do to make it better for myself and others, I'd love to help.

**Comment by ykalchevskiy** [comment]
Great to hear! 

But actually I meant:

```python
class RNCryptorError(Exception):
    """Base error for when anything goes wrong with RNCryptor."""


class DecryptionError(RNCryptorError):
    """Raised when bad data is inputted."""
```

Could you make it in this form?

**Comment by Skylled** [comment]
I had no idea that a docstring was a sufficient statement, to no longer need the pass statement. Ever learning!

**Comment by ykalchevskiy** [comment]
I've merged it. Thank you @Skylled!

**Pull request merged**
